version: "3"

services: 
    api_service:
        build: .
        command: npm run dev
        container_name: api_service
        ports: 
            - 4001:4001
        volumes: 
            - .:/usr/app
networks:
    default:
        external:
            name: linx-network
            
