version: "3.3"
services:
  db_products:
    image: mysql:8.0.1
    container_name: db_products
    environment: 
       MYSQL_ROOT_PASSWORD: "123"
       TZ: America/Manaus
    ports:
       - '3307:3306'
    volumes:
       - ./mysql-db:/var/lib/mysql  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
       - 8080:80
    links: 
      - db_products:db
networks:
   default:
      external:
         name: linx-network