version: "3.3"

services: 
    catalog:
        build: .
        command: npm run dev
        container_name: api_catalog
        ports: 
            - 4000:4000
        volumes: 
            - .:/usr/app
networks:
    default:
        external:
            name: linx-network
            
