version: "3"

services: 
    api_recommendation:
        build: .
        command: npm run dev
        container_name: api_recommendation
        ports: 
            - 4002:4002
        volumes: 
            - .:/usr/app
networks:
    default:
        external:
            name: linx-network
            
