version: "3"

services: 
    product:
        build: .
        command: npm run dev
        ports: 
            - 4000:4000
        volumes: 
            - .:/usr/app
networks:
    default:
        external:
            name: mysql-network
            
